[[redirects]]
  from = "/api"
  to = "https://e-commerce-qsq9.onrender.com/api"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"